services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: on-failure
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  discord-yt-bot:
    image: ghcr.io/dongcodebmt/discord-yt-bot:latest
    container_name: discord-yt-bot
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./.env:/app/.env
      - ./cookies.txt:/app/cookies.txt
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      - TZ=Asia/Ho_Chi_Minh
    depends_on:
      redis:
        condition: service_healthy
    restart: on-failure
